### ISSUE TITLE
Bug with coding strategy 

### ISSUE THREAD

**Issue by gulivero1773** [vapor-community/Imperial#81] opened 2021-04-09 10:11 UTC
When I use 
`
let encoder = JSONEncoder()
encoder.keyEncodingStrategy = .convertToSnakeCase
encoder.dateEncodingStrategy = .iso8601
ContentConfiguration.global.use(encoder: encoder, for: .json)

let decoder = JSONDecoder()
decoder.keyDecodingStrategy = .convertFromSnakeCase
decoder.dateDecodingStrategy = .iso8601
ContentConfiguration.global.use(decoder: decoder, for: .json)
`

in configure.swift I haw error - 
![image](https://user-images.githubusercontent.com/61082418/114164617-2bf8b200-9934-11eb-924c-446cd43330d6.png)

but when I don't use coding strategy  I got access token from Google. And it work, for testing I use project in book "Server-Side Swift with Vapor" (edition 3) Chapter 22: Google Authentication.

**Comment by 0xTim** [comment] 2021-04-12 09:46
Closing as this is a duplicate of #80

**Closed by 0xTim** 2021-04-12 09:46 UTC
